# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
version: '3'

silent: true
set: [pipefail]
shopt: [globstar]

vars:
  UV_ARGS: '{{.UV_ARGS | default ""}}'

tasks:
  fix-lint:
    desc: "Lint and fix (where possible) code style and formatting issues using ruff and mypy"
    cmds:
      - uv run {{.UV_ARGS}} ruff check --fix
      - uv run {{.UV_ARGS}} mypy --explicit-package-bases .
      - uv run {{.UV_ARGS}} ruff format

  lint:
    desc: "Check code style, formatting, and type hints without making changes"
    cmds:
      - uv run {{.UV_ARGS}} ruff check
      - uv run {{.UV_ARGS}} mypy --explicit-package-bases .
      - uv run {{.UV_ARGS}} ruff format --check

  test:
    desc: "Run pytest test suite with optional test path specification"
    cmds:
      # Run tests individually in separate processes to isolate global SLIM service state
      - |
        if [ -n "{{.TESTS}}" ]; then
          uv run {{.UV_ARGS}} pytest -s {{.TESTS}}
        else
          uv run {{.UV_ARGS}} pytest -s tests/test_client_server.py::test_mcp_client_server_connection || exit 1
          uv run {{.UV_ARGS}} pytest -s tests/test_client_server.py::test_mcp_client_server_reconnection || exit 1
        fi

  packaging:
    desc: "Build Python package and generate distribution artifacts"
    cmds:
      - uv build {{.UV_ARGS}}
